[book]
authors = ["Cagri Catik"]
language = "en"
multilingual = false
src = "src"
title = "Battery Management Systems"
[preprocessor.katex]

[output.html]
default-theme = "rust"
additional-css = ["src/custom.css"]


